[package]
name = "automatic_file_sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
chrono = "0.4"
fs = "0.0.5"
futures = "0.3.21"